version: '3.7'

services:
  server:
    image: traefik
    restart: unless-stopped
    deploy:
      # mode: global
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.traefik-dahsboard.rule=Host(`traefik.exlinetr.com`)"
        - "traefik.http.routers.traefik-dahsboard.service=api@internal"
        # - "traefik.http.routers.traefik-api.rule=Host(`traefik.exlinetr.com`) && PathPrefix(`/api`)"
        # - "traefik.http.routers.traefik-api.service=api@internal"
        - "traefik.http.routers.traefik-api.middlewares=traefik-dahsboard"
        - "traefik.http.middlewares.traefik-dahsboard.basicauth.users=furkaandogan:{SHA}90St/4Twu+l5Y9zfJQNDprYI+Ek="
        # # Dummy service for Swarm port detection. The port can be any valid integer value.
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
    command:
      # - "--log.level=DEBUG"
      - "--api=true"
      - "--api.debug=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.swarmModeRefreshSeconds=5s"
      - "--providers.docker.network=traefik_network"
      - "--providers.docker.watch=true"
      # - "--providers.docker.useBindPortIP=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    ports:
      - 8070:80
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  traefik_network:
    driver: overlay
    attachable: true
    external: true