version: '3.7'
services:
  zipkin:
    image: openzipkin/zipkin:latest
    restart: unless-stopped
    deploy:
      # mode: global
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 0
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.zipkin.service=zipkin"
        - "traefik.http.routers.zipkin.entrypoints=web"
        - "traefik.http.routers.zipkin.rule=Host(`zipkin.exlinetr.com`)"
        - "traefik.http.routers.zipkin.middlewares=zipkin"
        - "traefik.http.services.zipkin.loadbalancer.server.port=9411"
        - "traefik.http.services.zipkin.loadbalancer.server.scheme=http"
        - "traefik.http.middlewares.zipkin.basicauth.users=furkaandogan:{SHA}90St/4Twu+l5Y9zfJQNDprYI+Ek="
    networks:
      - exlinetr_infrustructure_logging_network
      - traefik_network

  server:
    image: traefik
    restart: unless-stopped
    deploy:
      # mode: global
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 0
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.traefik-dahsboard.rule=Host(`traefik.exlinetr.com`)"
        - "traefik.http.routers.traefik-dahsboard.service=api@internal"
        - "traefik.http.routers.traefik-api.middlewares=traefik-dahsboard"
        - "traefik.http.middlewares.traefik-dahsboard.basicauth.users=furkaandogan:{SHA}90St/4Twu+l5Y9zfJQNDprYI+Ek="
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
    command:
      # - "--log.level=DEBUG"
      - "--api=true"
      - "--api.debug=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--tracing.zipkin=true"
      - "--tracing.zipkin.httpEndpoint=http://zipkin:9411/api/v2/spans"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.fluentbit.address=:5170"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.swarmModeRefreshSeconds=5s"
      - "--providers.docker.network=traefik_network"
      - "--providers.docker.watch=true"
      # - "--providers.docker.useBindPortIP=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    ports:
      - 8070:80
      - 443:443
      - 5170:5170
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
  traefik_network:
    driver: overlay
    attachable: true
    external: true
  exlinetr_infrustructure_logging_network:
    name: "exlinetr_infrustructure_logging_network"
    external: true